version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak_container
    ports:
      - "8081:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command:
      - "start-dev"
