version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak_container
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - "start-dev"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    ports:
      - "8082:8082"
    depends_on:
      - keycloak
    command: ["java", "-jar", "app.jar", "--spring.profiles.active=local"]